### ISSUE TITLE
Refreshing the application always redirects to login and then home.

### ISSUE THREAD

**Issue by NikolaPeevski** [circleteach/circleteach#11]
No matter if you've logged or not refreshing simply goes to login and then home components.

**Comment by parlough** [comment]
Generally the goal should be that you don't need to refresh as components should update dynamically, but I do agree this should still be fixed. It will take some reworking of some of the application though, especially relation to authentication, as we check their authentication status before allowing them to navigate to a page, which I believe is the problem here as when they reload the page it needs to retrieve the user from our authentication service and Firebase and they aren't present at first, so it navigates them to the login page.

If we use a different method of checking, such as something in local storage, then the Firebase user/information is not ready yet and the page will be not be fully functional. We'll need to rework it so the Firebase state and our authentication service doesn't need to fully reload in this situation and we can access the necessary information immediately.

Thanks for the report, we'll give this a look when we get a chance.

**Comment by WillyWaser** [comment]
Reworking ? You can add a router guard that handles authentification so it lands on the home page and then redirects to login if necessary. All can be hidden behind a simple css spinner so the user has no clue where he is going. Also you can save the current route into local storage and load from there to prevent this nasty redirecting hell. @parlough

**Comment by parlough** [comment]
@WillyWaser I didn't think about letting the router guard wait until authentication is finished, I'll give that a try, thanks. It still should be quite quick as most of the Firebase information is cached locally, so might not even need a CSS spinner. Angular can handle going to the same route, the redirecting just occurs because of the guards.

**Comment by parlough** [comment]
Should be fixed by 3e2da98ff865af49799995b5a05f839e022223ba in the dev branch. Thanks for the report and suggestions!
