### ISSUE TITLE
Edit profile hangs, console is full of errors.

### ISSUE THREAD

**Issue by NikolaPeevski** [circleteach/circleteach#16]
When clicking edit profile the ui looks all wrong the first few seconds and the console keeps throwing errors.

**Comment by parlough** [comment]
This issue has not reappeared locally for us recently, I believe it was due to some changes I made in https://github.com/circleteach/circleteach/commit/b15bd36a9b412b31068dc978fa4c7b5da0983043 to fix the console errors or a related cleanup commit. If anyone experiences this issue again, please feel free to comment here or open a new issue. Thanks for the report!
