### ISSUE TITLE
Too long names make the container overflow.

### ISSUE THREAD

**Issue by WillyWaser** [circleteach/circleteach#17]
![image](https://user-images.githubusercontent.com/14194863/56815644-7f38cf00-6807-11e9-9c98-3fce77421d6d.png)

**Comment by parlough** [comment]
This should be fixed in this location at least, and I have added a reasonable max length that the UK has used for names. We will likely need to add some better overflow handling for names in other locations as well. Thanks for the bug report! 

Fixed in 4417d887750d8034cc41130742d850f25f91132c on the dev branch.
