### ISSUE TITLE
"Failed to sign up" when correctly singing up

### ISSUE THREAD

**Issue by sw8lde** [circleteach/circleteach#3]
Severity: medium

Description: When creating a new account to sign up, after hitting sign up an error message shows up that says "Failed to sign up", but then it logs in correctly with the new account.

**Comment by parlough** [comment]
Fixed by 3635672ca41fae11646248f28b3edfcb3e250df4 - Now only sets the message if truly failed to signup in response to a Firebase error, also should fix the color of the error message.

For now the fix is only in dev and will not go live until the next release.

Thanks for the bug report! We appreciate it.
